### ISSUE TITLE
Show a structure of algebra and handler 

### ISSUE THREAD

**Issue by AdrianRaFo** [frees-io/freestyle-template.g8#1]
The template should include an algebra with an implicit handler with the structure followed [here](https://github.com/frees-io/freestyle/blob/master/freestyle-effects/shared/src/main/scala/effects/either.scala)

**Comment by juanpedromoreno** [comment]
We should do this in the new gitter8 template for freestyle examples.

**Comment by AdrianRaFo** [comment]
May be useful to do it in both templates to show everybody the pattern to follow, internally and externally.
